package com.ouyang.scorerank.dao;

import com.ouyang.scorerank.dataobject.RankDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RankDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrank
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrank
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    int insert(RankDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrank
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    int insertSelective(RankDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrank
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    RankDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrank
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    int updateByPrimaryKeySelective(RankDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrank
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    int updateByPrimaryKey(RankDO record);

    List<RankDO> listScore();
}