package com.ouyang.scorerank.dataobject;

import java.util.Date;

public class RankDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrank.id
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrank.name
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrank.score
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrank.score_date
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    private Date scoreDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrank.id
     *
     * @return the value of userrank.id
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrank.id
     *
     * @param id the value for userrank.id
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrank.name
     *
     * @return the value of userrank.name
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrank.name
     *
     * @param name the value for userrank.name
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrank.score
     *
     * @return the value of userrank.score
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrank.score
     *
     * @param score the value for userrank.score
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrank.score_date
     *
     * @return the value of userrank.score_date
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    public Date getScoreDate() {
        return scoreDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrank.score_date
     *
     * @param scoreDate the value for userrank.score_date
     *
     * @mbg.generated Thu Jan 30 16:12:47 CST 2020
     */
    public void setScoreDate(Date scoreDate) {
        this.scoreDate = scoreDate;
    }
}